# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: neural_nets.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='neural_nets.proto',
  package='neuralnets',
  serialized_pb=_b('\n\x11neural_nets.proto\x12\nneuralnets\"\x14\n\x05Trace\x12\x0b\n\x03val\x18\x01 \x03(\x02\"\x1d\n\x05Spike\x12\t\n\x01t\x18\x01 \x01(\x05\x12\t\n\x01i\x18\x02 \x01(\x05\"\x9e\x01\n\x0cSpikingLayer\x12\x36\n\nlayer_type\x18\x01 \x01(\x0e\x32\".neuralnets.SpikingLayer.LayerType\x12\t\n\x01N\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\"=\n\tLayerType\x12\n\n\x06Simple\x10\x00\x12\x11\n\rHodgkinHuxley\x10\x01\x12\x11\n\rIntegrateFire\x10\x02\"\x86\x01\n\x07Synapse\x12.\n\x05stype\x18\x01 \x01(\x0e\x32\x1f.neuralnets.Synapse.SynapseType\x12\t\n\x01s\x18\x02 \x01(\x05\x12\t\n\x01t\x18\x03 \x01(\x05\x12\t\n\x01w\x18\x04 \x01(\x02\x12\t\n\x01\x64\x18\x05 \x01(\x02\"\x1f\n\x0bSynapseType\x12\x07\n\x03\x45XC\x10\x01\x12\x07\n\x03INH\x10\x02\"\x7f\n\x11SpikingConnection\x12\x0e\n\x06source\x18\x01 \x01(\x05\x12\x0e\n\x06target\x18\x02 \x01(\x05\x12%\n\x08synapses\x18\x03 \x03(\x0b\x32\x13.neuralnets.Synapse\x12\x14\n\x0cstdp_enabled\x18\x04 \x01(\x08\x12\r\n\x05\x61vg_w\x18\x05 \x01(\x02\"l\n\x0cNetworkState\x12(\n\x06layers\x18\x01 \x03(\x0b\x32\x18.neuralnets.SpikingLayer\x12\x32\n\x0b\x63onnections\x18\x02 \x03(\x0b\x32\x1d.neuralnets.SpikingConnection\"+\n\x06Raster\x12!\n\x06spikes\x18\x01 \x03(\x0b\x32\x11.neuralnets.Spike\"+\n\x08RGBImage\x12\t\n\x01R\x18\x01 \x03(\x05\x12\t\n\x01G\x18\x02 \x03(\x05\x12\t\n\x01\x42\x18\x03 \x03(\x05\"\xa9\x01\n\x11SimulationResults\x12\n\n\x02\x64t\x18\x01 \x01(\x02\x12\t\n\x01T\x18\x02 \x01(\x02\x12(\n\x06nstate\x18\x03 \x01(\x0b\x32\x18.neuralnets.NetworkState\x12!\n\x03img\x18\x04 \x01(\x0b\x32\x14.neuralnets.RGBImage\x12\"\n\x06spikes\x18\x05 \x03(\x0b\x32\x12.neuralnets.Raster\x12\x0c\n\x04iter\x18\x06 \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SPIKINGLAYER_LAYERTYPE = _descriptor.EnumDescriptor(
  name='LayerType',
  full_name='neuralnets.SpikingLayer.LayerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Simple', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HodgkinHuxley', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IntegrateFire', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=184,
  serialized_end=245,
)
_sym_db.RegisterEnumDescriptor(_SPIKINGLAYER_LAYERTYPE)

_SYNAPSE_SYNAPSETYPE = _descriptor.EnumDescriptor(
  name='SynapseType',
  full_name='neuralnets.Synapse.SynapseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EXC', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INH', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=351,
  serialized_end=382,
)
_sym_db.RegisterEnumDescriptor(_SYNAPSE_SYNAPSETYPE)


_TRACE = _descriptor.Descriptor(
  name='Trace',
  full_name='neuralnets.Trace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='neuralnets.Trace.val', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=53,
)


_SPIKE = _descriptor.Descriptor(
  name='Spike',
  full_name='neuralnets.Spike',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='neuralnets.Spike.t', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i', full_name='neuralnets.Spike.i', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=84,
)


_SPIKINGLAYER = _descriptor.Descriptor(
  name='SpikingLayer',
  full_name='neuralnets.SpikingLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layer_type', full_name='neuralnets.SpikingLayer.layer_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='N', full_name='neuralnets.SpikingLayer.N', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='neuralnets.SpikingLayer.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SPIKINGLAYER_LAYERTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=245,
)


_SYNAPSE = _descriptor.Descriptor(
  name='Synapse',
  full_name='neuralnets.Synapse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stype', full_name='neuralnets.Synapse.stype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='neuralnets.Synapse.s', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t', full_name='neuralnets.Synapse.t', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='w', full_name='neuralnets.Synapse.w', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='neuralnets.Synapse.d', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYNAPSE_SYNAPSETYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=382,
)


_SPIKINGCONNECTION = _descriptor.Descriptor(
  name='SpikingConnection',
  full_name='neuralnets.SpikingConnection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source', full_name='neuralnets.SpikingConnection.source', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='neuralnets.SpikingConnection.target', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='synapses', full_name='neuralnets.SpikingConnection.synapses', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stdp_enabled', full_name='neuralnets.SpikingConnection.stdp_enabled', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avg_w', full_name='neuralnets.SpikingConnection.avg_w', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=511,
)


_NETWORKSTATE = _descriptor.Descriptor(
  name='NetworkState',
  full_name='neuralnets.NetworkState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='layers', full_name='neuralnets.NetworkState.layers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connections', full_name='neuralnets.NetworkState.connections', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=513,
  serialized_end=621,
)


_RASTER = _descriptor.Descriptor(
  name='Raster',
  full_name='neuralnets.Raster',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spikes', full_name='neuralnets.Raster.spikes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=666,
)


_RGBIMAGE = _descriptor.Descriptor(
  name='RGBImage',
  full_name='neuralnets.RGBImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='R', full_name='neuralnets.RGBImage.R', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='G', full_name='neuralnets.RGBImage.G', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='B', full_name='neuralnets.RGBImage.B', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=668,
  serialized_end=711,
)


_SIMULATIONRESULTS = _descriptor.Descriptor(
  name='SimulationResults',
  full_name='neuralnets.SimulationResults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dt', full_name='neuralnets.SimulationResults.dt', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='T', full_name='neuralnets.SimulationResults.T', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nstate', full_name='neuralnets.SimulationResults.nstate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='img', full_name='neuralnets.SimulationResults.img', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spikes', full_name='neuralnets.SimulationResults.spikes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iter', full_name='neuralnets.SimulationResults.iter', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=714,
  serialized_end=883,
)

_SPIKINGLAYER.fields_by_name['layer_type'].enum_type = _SPIKINGLAYER_LAYERTYPE
_SPIKINGLAYER_LAYERTYPE.containing_type = _SPIKINGLAYER
_SYNAPSE.fields_by_name['stype'].enum_type = _SYNAPSE_SYNAPSETYPE
_SYNAPSE_SYNAPSETYPE.containing_type = _SYNAPSE
_SPIKINGCONNECTION.fields_by_name['synapses'].message_type = _SYNAPSE
_NETWORKSTATE.fields_by_name['layers'].message_type = _SPIKINGLAYER
_NETWORKSTATE.fields_by_name['connections'].message_type = _SPIKINGCONNECTION
_RASTER.fields_by_name['spikes'].message_type = _SPIKE
_SIMULATIONRESULTS.fields_by_name['nstate'].message_type = _NETWORKSTATE
_SIMULATIONRESULTS.fields_by_name['img'].message_type = _RGBIMAGE
_SIMULATIONRESULTS.fields_by_name['spikes'].message_type = _RASTER
DESCRIPTOR.message_types_by_name['Trace'] = _TRACE
DESCRIPTOR.message_types_by_name['Spike'] = _SPIKE
DESCRIPTOR.message_types_by_name['SpikingLayer'] = _SPIKINGLAYER
DESCRIPTOR.message_types_by_name['Synapse'] = _SYNAPSE
DESCRIPTOR.message_types_by_name['SpikingConnection'] = _SPIKINGCONNECTION
DESCRIPTOR.message_types_by_name['NetworkState'] = _NETWORKSTATE
DESCRIPTOR.message_types_by_name['Raster'] = _RASTER
DESCRIPTOR.message_types_by_name['RGBImage'] = _RGBIMAGE
DESCRIPTOR.message_types_by_name['SimulationResults'] = _SIMULATIONRESULTS

Trace = _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), dict(
  DESCRIPTOR = _TRACE,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.Trace)
  ))
_sym_db.RegisterMessage(Trace)

Spike = _reflection.GeneratedProtocolMessageType('Spike', (_message.Message,), dict(
  DESCRIPTOR = _SPIKE,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.Spike)
  ))
_sym_db.RegisterMessage(Spike)

SpikingLayer = _reflection.GeneratedProtocolMessageType('SpikingLayer', (_message.Message,), dict(
  DESCRIPTOR = _SPIKINGLAYER,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.SpikingLayer)
  ))
_sym_db.RegisterMessage(SpikingLayer)

Synapse = _reflection.GeneratedProtocolMessageType('Synapse', (_message.Message,), dict(
  DESCRIPTOR = _SYNAPSE,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.Synapse)
  ))
_sym_db.RegisterMessage(Synapse)

SpikingConnection = _reflection.GeneratedProtocolMessageType('SpikingConnection', (_message.Message,), dict(
  DESCRIPTOR = _SPIKINGCONNECTION,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.SpikingConnection)
  ))
_sym_db.RegisterMessage(SpikingConnection)

NetworkState = _reflection.GeneratedProtocolMessageType('NetworkState', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKSTATE,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.NetworkState)
  ))
_sym_db.RegisterMessage(NetworkState)

Raster = _reflection.GeneratedProtocolMessageType('Raster', (_message.Message,), dict(
  DESCRIPTOR = _RASTER,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.Raster)
  ))
_sym_db.RegisterMessage(Raster)

RGBImage = _reflection.GeneratedProtocolMessageType('RGBImage', (_message.Message,), dict(
  DESCRIPTOR = _RGBIMAGE,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.RGBImage)
  ))
_sym_db.RegisterMessage(RGBImage)

SimulationResults = _reflection.GeneratedProtocolMessageType('SimulationResults', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONRESULTS,
  __module__ = 'neural_nets_pb2'
  # @@protoc_insertion_point(class_scope:neuralnets.SimulationResults)
  ))
_sym_db.RegisterMessage(SimulationResults)


# @@protoc_insertion_point(module_scope)
